### PR TITLE
Add (Windows): Unicode and long-paths support

### PR DESCRIPTION
**Pull request by dnzbk**
@animetosho hi,

I added support for Unicode and long-paths on Windows - looking forward to your feedback,

NZBGet currently uses the par2cmdline library, which was vendored and patched to support Unicode some time ago. However, I’d like to switch to your improved fork as it offers better performance and maintenance. I’m aiming to use it as an external dependency, pulling it directly from the repository. To achieve this, I’ll need to refactor the code significantly, as par2cmdline-turbo isn’t currently designed for easy library integration. This will involve creating namespaces, separating header files for external and internal usage, and making other necessary changes.
Additionally, I’d like to transition from using msbuild and autotools to CMake, primarily due to its cross-platform compatibility and better dependency management.
I plan to implement these changes in my fork. Would you be interested in reviewing my changes and potentially incorporating them into your main repository?
I’d appreciate any feedback or suggestions you might have on this plan. Are there any aspects I might have overlooked?

### CODE REVIEW

**Comment by animetosho** [comment]
Really appreciate all the work you've put into this!

Sorry to ask this of you, but would you be able to file this PR to the [upstream project](https://github.com/Parchive/par2cmdline) instead? I don't actually intend to maintain par2cmdline - this fork is mostly a simple modification, but I intend to pull down changes made upstream.

I haven't looked at either, but you also might be interested in [this PR](https://github.com/Parchive/par2cmdline/pull/194) made there, which sounds like it tries to do something similar.

Please also file PRs for the other changes you intend to make upstream (unless any of them aren't applicable there and specifically related to this fork only).  
Unfortunately the upstream project is relatively dead, so there's a good chance it won't get reviewed or merged, however they are [seeking a maintainer](https://github.com/Parchive/par2cmdline#looking-for-maintainer); considering the amount of changes you intend to contribute, that might end up being easier for you.

**Comment by dnzbk** [comment]
I see, thanks.
I’d definitely like to use your improved version of par2cmdline. 
I’ll try to make improvements in my fork and we’ll see how things go.

**Comment by animetosho** [comment]
If it helps, I have CMake scripts for the [gf16](https://github.com/animetosho/ParPar/blob/dev/test/gf16/gf16_common.cmake) and [hasher](https://github.com/animetosho/ParPar/blob/dev/test/hasher/hasher_common.cmake) components.  
They're meant for the testing application, but it might help you if you're trying to do a full CMake migration.

**Comment by dnzbk** [comment]
That will be very helpful, thank you!

**Comment by Safihre** [comment]
@dnzbk We at SABnzbd have been waiting/hoping for par2cmdline-turbo with UTF8 and Long-path support, so if you could get this fixed in general also for the executable version, that would really help us ❤️

**Comment by dnzbk** [comment]
@Safihre 
Sure, that's the plan.

**Comment by animetosho** [comment]
Re [f65eb8a](https://github.com/animetosho/par2cmdline-turbo/pull/36/commits/f65eb8a35e182b08044e8f57ce2e1881ecc57e63): not freeing is actually intentional. `gfmat_init` initialises some lookup constants, but only [allocates once](https://github.com/animetosho/par2cmdline-turbo/blob/39ad5ded9cb3ace46f3de6b36481438b0754c57e/parpar/gf16/gfmat_coeff.c#L9-L12), so it's not a leak in the sense that it'll constantly grow.

`gfmat_free` is mostly there for test cases to stop ASAN complaining about a possible leak.  
Doing extra frees should be fine though - `gfmat_init` will have to recompute all the constants when it's called next, though I don't think that ever happens in par2cmdline.

Good on you for identifying it nonetheless.

**Comment by dnzbk** [comment]
@animetosho thanks for the feedback.

Yes, it's not that important if Par2 is used as a standalone command line tool, but I think it’s crucial when it used as a library as we do in NZBGet.

**Comment by animetosho** [comment]
> but I think it’s crucial when it used as a library as we do in NZBGet.

I'm interested in changing things to avoid issues, but I don't understand how this would be an issue when used as a library?

**Comment by dnzbk** [comment]
> I'm interested in changing things to avoid issues, but I don't understand how this would be an issue when used as a library?

Each new instance of Par2Repairer calls gfmat_init() as it aggregates PAR2Proc which leads to memory allocations without freeing it when PAR2Proc and Par2Repairer are destroyed.

**Comment by animetosho** [comment]
That's not quite it, only the first call allocates memory. Subsequent instances do not allocate memory.

**Comment by dnzbk** [comment]
> That's not quite it, only the first call allocates memory. Subsequent instances do not allocate memory.

Yes, you're right. Memory is indeed allocated only once. Valgrind was producing false positives as the memory is not actually explicitly freed up at program termination but this is not really something we should care about.
I'll revert my changes. 
Thanks for pointing that out.

**Comment by animetosho** [comment]
Ah that makes sense - thanks for letting me know! Maybe I can look at adding a Valgrind leak suppression file so that it doesn't turn up in reports (though people running Valgrind will need to know to include it).

**Comment by Safihre** [comment]
@dnzbk I saw you merged the nzbget PR. Is there also a way to get par2cmdline (turbo) with proper long path and utf8 support as a stand-alone binary? :)

**Comment by dnzbk** [comment]
@Safihre 
It’s still under testing, but sure, I can do that. Just give me a moment to make some adjustments in the repo.

**Comment by animetosho** [comment]
Ah yes, diagnosing failing Github Actions - lots of fun.  
Thanks for pointing that out - it looks like [this](https://github.com/animetosho/par2cmdline-turbo/commit/f94ea31ecce17d19f6931a58c1719a25758ae3a0) fixed it (in addition to setting the OS to `macos-13` as newer versions may be ARM64).

**Comment by Safihre** [comment]
@animetosho still can't persuade you to merge this into turbo directly? 🤗

**Comment by animetosho** [comment]
I had a quick look at the changes made in nzbgetcom's fork. I mostly don't get the intention behind moving the headers around, and this could make future updates a little finicky. So I'm a bit reluctant to use the repository as an upstream at the moment.

For @Safihre's purposes, using the nzbgetcom fork might do everything you need it to.

I'm reiterating, but appreciate the work @dnzbk has put in.

**Comment by dnzbk** [comment]
The [nzbget](https://github.com/nzbgetcom/par2cmdline-turbo/tree/nzbget) branch includes some changes (signals, namespaces  headers refactoring and etc.) specific to nzbget and is not needed by anyone else except nzbget itself.
The [utf8](https://github.com/nzbgetcom/par2cmdline-turbo/tree/utf8) branch is a “vanilla” Par2-turbo + better UTF-8 support on Windows, which I used to build the [binaries](https://github.com/nzbgetcom/par2cmdline-turbo/releases/tag/v1.1.1-utf8) for @Safihre and maybe someone else.

**Comment by animetosho** [comment]
Ah I see, thanks for the explanation!

**Comment by Safihre** [comment]
@animetosho we can merge the utf8 branch?

**Comment by Safihre** [comment]
@dnzbk I tried it but it still has a problem with our unicode-test case NZB (which works with Multipar).
I also tried it in the latest nzbget build, and there it fails to. So it seems a problem with the utf8 code.
https://sabnzbd.org/tests/unicode_rar_broken.nzb

**Comment by dnzbk** [comment]
@Safihre Thanks, I'll take a look.

**Comment by dnzbk** [comment]
@Safihre Should be fixed now. At least it does work in nzbget now. Please [test](https://github.com/nzbgetcom/par2cmdline-turbo/releases) it out.

**Comment by Safihre** [comment]
Success!

**Comment by Safihre** [comment]
Now we can finally switch to par2cmdline (from Multipar) for the Windows release of SABnzbd. It was the only platform where we didn't use it yet 🥳
But for maintainability I think we will have to fork turbo also in `sabnzbd` Github organization, if this doesn't become part of base turbo.

**Comment by animetosho** [comment]
If you're happy with maintaining a fork, I can point this repository to that as upstream.  
(I'm a bit reluctant to point to the nzbget branch as upstream due to changes to ParPar code)

**Pull request closed without merging**
